### ISSUE TITLE
error code 429

### ISSUE THREAD

**Issue by floflobal** [chashtag/PiCash#5]
hello, when i start earnapp with the command:
docker exec -ti picash earnapp start

i have this error message:

✔ IP detected
⠴ Registering Device...Error: Request failed with status code 429
    at createError (/snapshot/svc/earnapp_cli/earnapp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/svc/earnapp_cli/earnapp/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/svc/earnapp_cli/earnapp/node_modules/axios/lib/adapters/http.js:293:11)

**Comment by chashtag** [comment]
429 is a rate limiting error code, with the container already running earnapp should be running in the background

**Comment by floflobal** [comment]
It's OK now. Thanks

**Comment by chashtag** [comment]
Please feel free to re-open this ticket if it happens again
