### ISSUE TITLE
PacketStream errors in log about parsing PS_ID 

### ISSUE THREAD

**Issue by juniormayhe** [chashtag/PiCash#6]
Hi 👋 Any idea what is these messages about with `docker logs -f picash` ?

```
goroutine 1 [running]:
main.init.0()
 /home/developer/git/go-workspace/src/gitlab.com/packetstream/ecosystem/exit-node/main.go:59 +0x2a3
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
, 0 exiting
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
panic: strconv.Atoi: parsing "42cy": invalid syntax

goroutine 1 [running]:
main.init.0()
 /home/developer/git/go-workspace/src/gitlab.com/packetstream/ecosystem/exit-node/main.go:59 +0x2a3
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
, 0 exiting
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
panic: strconv.Atoi: parsing "42cy": invalid syntax
```

This error happens after starting (./run.sh) when packetstream has been actived in settings.conf:
```
# Packet Stream
USE_PACKET_STREAM=y
PS_ID=42cy
```

For now, I had to turn this off and spin up a different docker image:
```
docker run -d --restart always --name packetstream -e CID=42cy packetstream/psclient:latest
$ docker logs -f packetstream
aarch64
{"ok":false,"message":"PacketStream is initializing..."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}
```

**Comment by chashtag** [comment]
Sorry about that, Packetstream has an additional step to calculate your `CID` the launcher script has been updated to use it.
Thanks for catching that!
